# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d7c0a4edc719a8dafbc460314929504ef6241eab1395e9f99d81b132c5511e3d7248e72c548b48a14a44c724656a72a9fb2ae9bafcaaba1269bb327e372181

test:
  secret_key_base: 65a9663e36182fdab7d8d62b9f136485799e08165320da84164530419b6f275e8737b4332fd84ee11c407bf1f4c6a6ee3819463b2aa7d102364273ebc28f837c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
